In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3])

In [6]:
b=np.array([(1.2,2,3),(4,5,6)],dtype=float)

In [7]:
c=np.array([[(1.2,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [12]:
e=np.linspace(0,2,9)

In [13]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [16]:
x=np.eye(3)

In [17]:
y=np.random.random((2,2))

In [18]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
y

array([[0.95664808, 0.95184093],
       [0.68192083, 0.01477401]])

In [20]:
np.shape(a)

(3,)

In [21]:
np.shape(b)

(2, 3)

In [22]:
np.shape(c)

(2, 2, 3)

In [23]:
np.ndim(a)

1

In [24]:
np.ndim(b)

2

In [25]:
np.ndim(c)

3

In [26]:
np.size(a)

3

In [27]:
np.size(b)

6

In [28]:
np.size(c)

12

In [29]:
a.dtype

dtype('int32')

In [30]:
b.dtype

dtype('float64')

In [31]:
c.dtype

dtype('float64')

In [32]:
a.dtype.name

'int32'

In [33]:
b.dtype.name

'float64'

In [34]:
c.dtype.name

'float64'

In [35]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
x=np.multiply(b,b)

In [37]:
x

array([[ 1.44,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [38]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.add(a,b)

array([[2.2, 4. , 6. ],
       [5. , 7. , 9. ]])

In [40]:
np.subtract(a,b)

array([[-0.2,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [41]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [42]:
np.sqrt(b)

array([[1.09544512, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
np.sqrt(c)

array([[[1.09544512, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [44]:
np.add(a,b)

array([[2.2, 4. , 6. ],
       [5. , 7. , 9. ]])

In [45]:
np.min(a)

np.int32(1)

In [46]:
np.int32(1)

np.int32(1)

In [47]:
np.max(a)

np.int32(3)

In [48]:
np.cumsum(a)

array([1, 3, 6])

In [49]:
np.mean(a)

np.float64(2.0)

In [50]:
np.median(a)

np.float64(2.0)

In [51]:
np.std(a)

np.float64(0.816496580927726)